// Grok Night, shared with this machine's Herdr and herdr-reviewr setup.
// Palette source: xai-org/grok-build, Apache-2.0; see THIRD_PARTY_NOTICES.md.
export const GROK_NIGHT = {
  base: "#0a0a0a",
  panel: "#141414",
  surface0: "#242424",
  surface1: "#2e2e33",
  surface2: "#363636",
  border: "#505058",
  muted: "#6c6c6c",
  secondary: "#a8a8a8",
  text: "#e1e1e1",
  accent: "#c8c8c8",
  lavender: "#8b9cb3",
  mauve: "#bb9af7",
  red: "#f7768e",
  green: "#9ece6a",
  yellow: "#e0af68",
  blue: "#7aa2f7",
  teal: "#1abc9c",
  peach: "#ff9e64",
} as const;

// OpenTUI MarkdownRenderable scopes, colored like herdr-reviewr's pulldown-cmark theme.
export const GROK_NIGHT_MARKDOWN = {
  default: { fg: GROK_NIGHT.text },
  keyword: { fg: GROK_NIGHT.red, bold: true },
  string: { fg: GROK_NIGHT.green },
  comment: { fg: GROK_NIGHT.muted, italic: true },
  number: { fg: GROK_NIGHT.peach },
  function: { fg: GROK_NIGHT.blue },
  type: { fg: GROK_NIGHT.teal },
  operator: { fg: GROK_NIGHT.red },
  variable: { fg: GROK_NIGHT.text },
  property: { fg: GROK_NIGHT.blue },
  "punctuation.bracket": { fg: GROK_NIGHT.text },
  "punctuation.delimiter": { fg: GROK_NIGHT.secondary },
  "markup.heading": { fg: GROK_NIGHT.mauve, bold: true },
  "markup.heading.1": { fg: GROK_NIGHT.mauve, bold: true },
  "markup.heading.2": { fg: GROK_NIGHT.mauve, bold: true },
  "markup.heading.3": { fg: GROK_NIGHT.lavender, bold: true },
  "markup.bold": { fg: GROK_NIGHT.text, bold: true },
  "markup.strong": { fg: GROK_NIGHT.text, bold: true },
  "markup.italic": { fg: GROK_NIGHT.text, italic: true },
  "markup.list": { fg: GROK_NIGHT.peach },
  "markup.quote": { fg: GROK_NIGHT.muted, italic: true },
  "markup.raw": { fg: GROK_NIGHT.yellow, bg: GROK_NIGHT.surface0 },
  "markup.raw.block": { fg: GROK_NIGHT.yellow, bg: GROK_NIGHT.surface0 },
  "markup.raw.inline": { fg: GROK_NIGHT.yellow, bg: GROK_NIGHT.surface0 },
  "markup.link": { fg: GROK_NIGHT.blue, underline: true },
  "markup.link.label": { fg: GROK_NIGHT.yellow, underline: true },
  "markup.link.url": { fg: GROK_NIGHT.blue, underline: true },
  "diff.plus": { fg: GROK_NIGHT.green },
  "diff.minus": { fg: GROK_NIGHT.red },
  conceal: { fg: GROK_NIGHT.muted },
  "punctuation.special": { fg: GROK_NIGHT.muted },
} as const;
