// owned by: alias agent
// Static completion scripts, generated from the registry. Nothing is looked up
// at completion time — the script is a snapshot of the command surface, so a
// tab never costs an API call. Regenerate after upgrading `lin`.

import { EXIT, LinError, raw } from "../out.ts";
import { allCommands, defineCommand, GLOBAL_FLAGS, type CommandSpec, type FlagSpec } from "../registry.ts";

export const SHELLS = ["bash", "zsh", "fish"] as const;
export type Shell = (typeof SHELLS)[number];

// --- the command surface, derived from the registry --------------------------

interface Word {
  word: string;
  doc: string;
}

function nounOf(command: CommandSpec): string {
  return command.name.split(" ")[0] as string;
}

function verbOf(command: CommandSpec): string | undefined {
  return command.name.split(" ")[1];
}

/** Everything valid in first position: nouns, one-word commands, aliases. */
export function roots(commands: readonly CommandSpec[]): Word[] {
  const words = new Map<string, string>();

  for (const command of commands) {
    const noun = nounOf(command);
    const verb = verbOf(command);
    // A one-word command documents its own noun; `cache warm` only implies one.
    if (verb === undefined) words.set(noun, command.summary);
    else if (!words.has(noun)) words.set(noun, `${noun} commands`);
    for (const alias of command.aliases ?? []) words.set(alias, command.summary);
  }

  return [...words].sort(([a], [b]) => a.localeCompare(b)).map(([word, doc]) => ({ word, doc }));
}

/** Nouns that take a verb, with the verbs they take. */
export function verbs(commands: readonly CommandSpec[]): Map<string, Word[]> {
  const byNoun = new Map<string, Word[]>();

  for (const command of [...commands].sort((a, b) => a.name.localeCompare(b.name))) {
    const verb = verbOf(command);
    if (verb === undefined) continue;
    const noun = nounOf(command);
    const list = byNoun.get(noun) ?? [];
    list.push({ word: verb, doc: command.summary });
    byNoun.set(noun, list);
  }

  return byNoun;
}

function flagEntries(command: CommandSpec): [string, FlagSpec][] {
  return Object.entries(command.flags ?? {});
}

/** `--mine`, `-t`, ... for one flag table. */
function flagWords(specs: Record<string, FlagSpec>): string[] {
  const words: string[] = [];
  for (const [name, spec] of Object.entries(specs)) {
    words.push(`--${name}`);
    if (spec.short) words.push(`-${spec.short}`);
  }
  return words;
}

function withFlags(commands: readonly CommandSpec[]): CommandSpec[] {
  return [...commands]
    .filter((command) => flagEntries(command).length > 0)
    .sort((a, b) => a.name.localeCompare(b.name));
}

// --- bash --------------------------------------------------------------------

function bash(commands: readonly CommandSpec[]): string {
  const lines = [
    "# bash completion for lin, generated by: lin completions bash",
    "# install: lin completions bash > ~/.local/share/bash-completion/completions/lin",
    "",
    "_lin() {",
    "  local cur noun verb key words",
    '  cur="${COMP_WORDS[COMP_CWORD]}"',
    '  noun="${COMP_WORDS[1]:-}"',
    '  verb="${COMP_WORDS[2]:-}"',
    '  key="$noun"',
    '  if [ -n "$verb" ] && [ "${verb#-}" = "$verb" ]; then key="$noun $verb"; fi',
    "",
    '  if [ "${cur#-}" != "$cur" ]; then',
    '    case "$key" in',
  ];

  for (const command of withFlags(commands)) {
    lines.push(`      '${command.name}') words='${flagWords(command.flags ?? {}).join(" ")}' ;;`);
  }

  lines.push(
    "      *) words='' ;;",
    "    esac",
    `    words="$words ${flagWords(GLOBAL_FLAGS).join(" ")}"`,
    '  elif [ "$COMP_CWORD" -eq 1 ]; then',
    `    words='${roots(commands).map((root) => root.word).join(" ")}'`,
    "  else",
    '    case "$noun" in',
  );

  for (const [noun, list] of verbs(commands)) {
    lines.push(`      '${noun}') words='${list.map((verb) => verb.word).join(" ")}' ;;`);
  }

  lines.push(
    "      *) words='' ;;",
    "    esac",
    "  fi",
    "",
    '  COMPREPLY=($(compgen -W "$words" -- "$cur"))',
    "}",
    "",
    "complete -F _lin lin",
  );

  return `${lines.join("\n")}\n`;
}

// --- zsh ---------------------------------------------------------------------

function zsh(commands: readonly CommandSpec[]): string {
  const lines = [
    "#compdef lin",
    "# zsh completion for lin, generated by: lin completions zsh",
    "# install: lin completions zsh > ~/.zfunc/_lin  (with ~/.zfunc on $fpath)",
    "",
    "_lin() {",
    "  local cur noun verb key",
    '  cur="${words[CURRENT]}"',
    '  noun="${words[2]}"',
    '  verb="${words[3]}"',
    '  key="$noun"',
    '  [[ -n "$verb" && "$verb" != -* ]] && key="$noun $verb"',
    "",
    '  if [[ "$cur" == -* ]]; then',
    '    case "$key" in',
  ];

  for (const command of withFlags(commands)) {
    lines.push(`      '${command.name}') compadd -- ${flagWords(command.flags ?? {}).join(" ")} ;;`);
  }

  lines.push(
    "    esac",
    `    compadd -- ${flagWords(GLOBAL_FLAGS).join(" ")}`,
    "    return",
    "  fi",
    "",
    "  if (( CURRENT == 2 )); then",
    `    compadd -- ${roots(commands).map((root) => root.word).join(" ")}`,
    "    return",
    "  fi",
    "",
    '  case "$noun" in',
  );

  for (const [noun, list] of verbs(commands)) {
    lines.push(`    '${noun}') compadd -- ${list.map((verb) => verb.word).join(" ")} ;;`);
  }

  lines.push(
    "  esac",
    "}",
    "",
    'if [ "${funcstack[1]}" = "_lin" ]; then',
    '  _lin "$@"',
    "fi",
  );

  return `${lines.join("\n")}\n`;
}

// --- fish --------------------------------------------------------------------

/** fish reads single quotes literally apart from \\ and \'. */
function fishQuote(text: string): string {
  return `'${text.replace(/\\/g, "\\\\").replace(/'/g, "\\'").replace(/\s+/g, " ")}'`;
}

function fishFlag(condition: string, name: string, spec: FlagSpec): string {
  const parts = ["complete -c lin"];
  if (condition) parts.push(`-n ${fishQuote(condition)}`);
  if (spec.short) parts.push(`-s ${spec.short}`);
  parts.push(`-l ${name}`);
  if (spec.type !== "boolean") parts.push("-r");
  parts.push(`-d ${fishQuote(spec.doc)}`);
  return parts.join(" ");
}

function fish(commands: readonly CommandSpec[]): string {
  const byNoun = verbs(commands);
  const lines = [
    "# fish completion for lin, generated by: lin completions fish",
    "# install: lin completions fish > ~/.config/fish/completions/lin.fish",
    "",
    "complete -c lin -f",
    "",
    "# global flags",
  ];

  for (const [name, spec] of Object.entries(GLOBAL_FLAGS)) lines.push(fishFlag("", name, spec));

  lines.push("", "# nouns, aliases and one-word commands");
  for (const root of roots(commands)) {
    lines.push(
      `complete -c lin -n '__fish_use_subcommand' -a ${root.word} -d ${fishQuote(root.doc)}`,
    );
  }

  for (const [noun, list] of byNoun) {
    const others = list.map((verb) => verb.word).join(" ");
    lines.push("", `# ${noun} verbs`);
    for (const verb of list) {
      const condition = `__fish_seen_subcommand_from ${noun}; and not __fish_seen_subcommand_from ${others}`;
      lines.push(
        `complete -c lin -n ${fishQuote(condition)} -a ${verb.word} -d ${fishQuote(verb.doc)}`,
      );
    }
  }

  for (const command of withFlags(commands)) {
    const noun = nounOf(command);
    const verb = verbOf(command);
    const condition =
      verb === undefined
        ? `__fish_seen_subcommand_from ${noun}`
        : `__fish_seen_subcommand_from ${noun}; and __fish_seen_subcommand_from ${verb}`;
    lines.push("", `# ${command.name} flags`);
    for (const [name, spec] of flagEntries(command)) lines.push(fishFlag(condition, name, spec));
  }

  return `${lines.join("\n")}\n`;
}

// --- command -----------------------------------------------------------------

const GENERATORS: Record<Shell, (commands: readonly CommandSpec[]) => string> = { bash, zsh, fish };

export function renderCompletions(shell: Shell, commands: readonly CommandSpec[]): string {
  return GENERATORS[shell](commands);
}

export default defineCommand({
  name: "completions",
  group: "meta",
  summary: "print a shell completion script for bash, zsh, or fish",
  args: [{ name: "shell", doc: "bash, zsh, or fish", required: true }],
  examples: [
    "lin completions zsh > ~/.zfunc/_lin",
    "lin completions fish > ~/.config/fish/completions/lin.fish",
  ],
  run({ args }) {
    const shell = args[0];
    if (shell === undefined || !SHELLS.includes(shell as Shell)) {
      throw new LinError(
        EXIT.input,
        shell === undefined ? "no shell given" : `no completions for "${shell}"`,
        `shells: ${SHELLS.join(", ")}`,
      );
    }

    raw(renderCompletions(shell as Shell, allCommands()));
  },
});
